version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  build:
    executor: node-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Check for package.json
          command: ls -la ~/project/package.json

      - run:
          name: Debug Files After Checkout
          command: ls -la ~/project
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Verify Vite Installation
          command: npx vite --version
      - run:
          name: Build Project
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist


    deploy:
      executor: node-executor
      working_directory: ~/project
      steps:
       - checkout
       - attach_workspace:
          at: ~/project
       - add_ssh_keys:
          fingerprints:
            - "SHA256:q6IqW+A5//boOJzD4pEJ8clSiTiDfpdW7FrBSNzsfOQ"
       - run:
          name: Ensure target directory exists
          command: ssh -o StrictHostKeyChecking=no ec2-user@54.174.92.185 "mkdir -p /var/www/html"
       - run:
          name: Deploy to EC2
          command: scp -o StrictHostKeyChecking=no -r ~/project/dist/* ec2-user@54.174.92.185:/var/www/html



workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build



