version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  build:
    executor: node-executor
    working_directory: ~/project  # ✅ Ensure working directory is set
    steps:
      - checkout
      - run:
          name: Check Directory Structure
          command: ls -la  # ✅ Debugging step to list files
      - run:
          name: Check for package.json
          command: cat package.json || echo "package.json not found!"  # ✅ Debugging step
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  deploy:
    executor: node-executor
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Verify Build Files Before Deploy
          command: ls -la build/ || echo "Build folder not found!"  # ✅ Debugging step
      - run:
          name: Deploy to EC2
          command: |
            scp -o StrictHostKeyChecking=no -r build/* ec2-user@44.203.66.201:/var/www/html

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build


