version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17  # ✅ Updated image

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "SHA256:q6IqW+A5//boOJzD4pEJ8clSiTiDfpdW7FrBSNzsfOQ"  # Replace with your CircleCI SSH key fingerprint
      - run:
          name: Deploy to EC2
          command: |
            scp -o StrictHostKeyChecking=no -r build/* ec2-user@44.203.66.201:/var/www/html

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

