version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to EC2
          command: |
            scp -r -i ~/.ssh/your-key.pem build/* ec2-user@44.203.66.201:/var/www/html

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build


