version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18  # Updated CircleCI node image

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Check Vite installation
          command: npx vite --version
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist  # Ensure 'dist' directory is saved for deployment

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Vercel
          command: |
            npm install -g vercel
            vercel --prod --token $VERCEL_TOKEN

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
